### ISSUE TITLE
Adding Cheerio to chrome extension using this plugin causes an exception

### ISSUE THREAD

**Issue by imgregduh** [bumble-org/rollup-plugin-chrome-extension#9]
**Describe the bug**
I am using the following:

```
// rollup.config.js
import resolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'

import {chromeExtension} from 'rollup-plugin-chrome-extension'

export default {
  input: 'src/manifest.json',
  output: {
    dir: 'dist',
    format: 'esm',
  },
  // always put chromeExtension() before other plugins
  plugins: [
    chromeExtension(),
    resolve(),
    commonjs()
  ],
}
```
```
background.js
import cheerio from 'cheerio'

console.log('background service running');

chrome.browserAction.onClicked.addListener(buttonClicked);

function buttonClicked(tab) {
  console.log('activate');
  chrome.tabs.sendMessage(tab.id, 'activate');
}

chrome.runtime.onMessage.addListener((message, sender) => {
  console.log(message);
  if (message.title === 'open') {
    const doc = cheerio.load(message.url);
    console.log(doc);
    chrome.tabs.create({url: message.url})
  }
});
```

This exception appears when I `yarn build`

```
src/manifest.json → dist...
[!] Error: Unexpected token (Note that you need rollup-plugin-json to import JSON files)
node_modules\cheerio\package.json (2:8)
1: {
2:   "name": "cheerio",
           ^
3:   "version": "1.0.0-rc.3",
4:   "description": "Tiny, fast, and elegant implementation of core jQuery designed specifically for the server",
Error: Unexpected token (Note that you need rollup-plugin-json to import JSON files)
    at error (D:\workspace\get-magnet\node_modules\rollup\dist\rollup.js:5330:30)
    at Module.error (D:\workspace\get-magnet\node_modules\rollup\dist\rollup.js:9612:9)
    at tryParse (D:\workspace\get-magnet\node_modules\rollup\dist\rollup.js:9524:16)
    at Module.setSource (D:\workspace\get-magnet\node_modules\rollup\dist\rollup.js:9841:33)
    at D:\workspace\get-magnet\node_modules\rollup\dist\rollup.js:12622:20
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
1. Following the instructions on the readme
2. `yarn add cheerio`
3. reference cheerio somewhere in either background or content
4. `yarn build`

**Desktop (please complete the following information):**
 - OS: Win 10

**Additional context**
I followed the read general instructions from the readme and it was working fine till I added cheerio.  I tried adding `rollup-plugin-json` but that gave a ton of warning and threw execptions when loading into chrome.

**Comment by jacksteamdev** [comment]
Interesting. It looks like cheerio's `package.json` is getting imported instead of it's entry file. I'll try to repro this issue this afternoon.

Thanks for going to the effort to create a great issue! For some reason we weren't getting notified by GitHub of issues on this repo, but I think we've resolved _that_ problem now.

**Comment by jacksteamdev** [comment]
It seems that this is not a `rollup-plugin-chrome-extension` bug. I was able to reproduce this error with the following config:

```javascript
```

**Comment by jacksteamdev** [comment]
It seems that this is not a `rollup-plugin-chrome-extension` bug.

I was able to reproduce this error with the following config, which simply builds `src/background.js` directly:

```javascript
// rollup.config.js
import resolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'

export default {
  input: 'src/background.js',
  output: {
    dir: 'dist',
    format: 'esm',
  },
  plugins: [
    resolve(),
    commonjs()
  ],
}
```
